<a href="https://colab.research.google.com/github/JoyNgaru/ai_engineering/blob/main/counterfactuals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install alibi[tensorflow]



  Using cached alibi-0.9.6-py3-none-any.whl.metadata (22 kB)
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
  Using cached blis-0.7.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
  Using cached scikit_image-0.22.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
  Using cached pillow-10.4.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
  Using cached transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
INFO: pip is looking at multiple versions of alibi[tensorflow] to determine which version is compatible with other requirements. This could take a while.
  Using cached alibi-0.9.5-py3-none-any.whl.metadata (22 kB)
  Using cached pydantic-1.10.26-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (155 kB)
  Using cached alibi-0.9.4-py3-none-any.whl.metadata (22 kB)
  Using cached sci

In [ ]:
!pip install pandas==1.5.3



  Using cached pandas-1.5.3.tar.gz (5.2 MB)
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


In [ ]:
!pip install --upgrade pip setuptools wheel
!pip install pandas==2.2.2
!pip install git+https://github.com/SeldonIO/alibi.git



  Using cached setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 23.5 MB/s eta 0:00:00
Using cached setuptools-82.0.1-py3-none-any.whl (1.0 MB)
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.


  Cloning https://github.com/SeldonIO/alibi.git to /tmp/pip-req-build-bzv3qsnz
  Running command git clone --filter=blob:none --quiet https://github.com/SeldonIO/alibi.git /tmp/pip-req-build-bzv3qsnz
  Resolved https://github.com/SeldonIO/alibi.git to commit 99c3421d7c971c85893625e37da1133e7ddf1779
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
  Using cached blis-0.7.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
  Using cached scikit_image-0.22.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
  Using cached pillow-10.4.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
  Using cached transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━

In [1]:
!pip install --upgrade numpy



  Using cached numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Using cached numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.2.5 requires numpy<2.0.0,>=1.19.0; python_version >= "3.9", but you have numpy 2.4.3 which is incompatible.
alibi 0.9.7.dev0 requires numpy<2.0.0,>=1.16.2, but you have numpy 2.4.3 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.3 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.4.3 which is incompatible.


In [1]:
!pip install --upgrade git+https://github.com/SeldonIO/alibi.git


  Cloning https://github.com/SeldonIO/alibi.git to /tmp/pip-req-build-s7wk6qk4
  Running command git clone --filter=blob:none --quiet https://github.com/SeldonIO/alibi.git /tmp/pip-req-build-s7wk6qk4
  Resolved https://github.com/SeldonIO/alibi.git to commit 99c3421d7c971c85893625e37da1133e7ddf1779
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.3
    Uninstalling numpy-2.4.3:
      Successfully uninstalled numpy-2.4.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tobler 0.13.0 requires numpy>=2.0, but you 

In [1]:
import numpy as np, alibi
print("NumPy version:", np.__version__)
print("Alibi version:", alibi.__version__)


NumPy version: 1.26.4
Alibi version: 0.9.7.dev0


In [2]:
#!pip install alibi[tensorflow]
# import the necessary Libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from alibi.explainers import CounterfactualRL, Counterfactual
from matplotlib import pyplot as plt
import tensorflow as tf
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

# load the dataset
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
columns = data.feature_names
df['target'] = data.target
df.head()

y = data.target
x = data.data

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# the function for creating an autoencoder
from tensorflow.keras.layers import Dense
from tensorflow import keras

ENCODING_DIM = 7
BATCH_SIZE = 64
EPOCHS = 10

class AE(keras.Model):
    def __init__(self, encoder: keras.Model, decoder: keras.Model, **kwargs) -> None:
        super().__init__(**kwargs)
        self.encoder = encoder
        self.decoder = decoder

    def call(self, x: tf.Tensor, **kwargs):
        z = self.encoder(x)
        x_hat = self.decoder(z)
        return x_hat

def make_ae():
    len_input_output = x_train_scaled.shape[-1]

    encoder = keras.Sequential()
    encoder.add(Dense(units=ENCODING_DIM*2, activation="relu", input_shape=(len_input_output, )))
    encoder.add(Dense(units=ENCODING_DIM, activation="relu"))

    decoder = keras.Sequential()
    decoder.add(Dense(units=ENCODING_DIM*2, activation="relu", input_shape=(ENCODING_DIM, )))
    decoder.add(Dense(units=len_input_output, activation="linear"))

    ae = AE(encoder=encoder, decoder=decoder)
    ae.compile(optimizer='adam', loss='mean_squared_error')

    history = ae.fit(
        x_train_scaled, x_train_scaled,
        batch_size=BATCH_SIZE,
        epochs=EPOCHS,
        verbose=True,
    )
    # loss = history.history['loss']
    # plt.plot(loss)
    # plt.xlabel('Epoch')
    # plt.ylabel('MSE-Loss')
    return ae

# Create the autoencoder
ae = make_ae()

# A function to show the differences between any two instances
def compare_instances(x, cf):
    """
    Show the difference in values between two instances.
    """
    x = x.astype('float64')
    cf = cf.astype('float64')
    for f, v1, v2 in zip(columns, x[0], cf[0]):
        print(f'{f:<25} instance: {round(v1, 3):^10} counter factual: {round(v2, 3):^10} difference: {round(v1 - v2, 7):^5}')

# Create and train a Random Forest model
model = RandomForestClassifier(random_state=42)
model.fit(x_train_scaled, y_train)

# create a prediction function
predict_fn = lambda x: model.predict_proba(x.reshape(x.shape[0], -1))

pred = predict_fn(x_test_scaled)[0:5]
print(pred)

# A function to reshape an instance to the format required by the model
def reshape(x):
    return x.reshape(x.shape[0], -1)

cfrl_explainer = CounterfactualRL(
    predictor=predict_fn,  # The model to explain
    encoder=ae.encoder,    # The encoder
    decoder=ae.decoder,    # The decoder
    latent_dim=7,          # The dimension of the autoencoder latent space
    coeff_sparsity=0.5,    # The coefficient of sparsity
    coeff_consistency=0.5, # The coefficient of consistency
    train_steps=10,        # The number of training steps
    batch_size=10,         # Changed from 24
)

# Remove the reshape function call:
cfrl_explainer.fit(X=x_train_scaled) # Pass the data directly

# Explain an instance
x = x_test_scaled[0].reshape(1, -1)
result_cfrl = cfrl_explainer.explain(X=x, Y_t=np.array([1]))
print("Instance class prediction:", data.target_names[model.predict(x)])
countFactPred = model.predict(result_cfrl.data['cf']['X'])[0].argmax()
print("Counterfactual class prediction:", data.target_names[countFactPred])
x = scaler.inverse_transform(x)
counterFact = scaler.inverse_transform(result_cfrl.data['cf']['X'])

features = columns
compare_instances(x, counterFact)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step - loss: 1.0939
Epoch 2/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 1.0737
Epoch 3/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1.0552
Epoch 4/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 1.0378
Epoch 5/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 1.0212
Epoch 6/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 1.0059
Epoch 7/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.9924
Epoch 8/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - loss: 0.9797
Epoch 9/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.9680
Epoch 10/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 0.9564 
[[0.   0.99 0.01]
 [1.   0.   0.  ]
 [0.   0.04 0.96]
 [0.   0.99 0.01]
 [0.   0.89 0.11]]


100%|██████████| 1/1 [00:00<00:00,  7.65it/s]


Instance class prediction: ['versicolor']
Counterfactual class prediction: setosa
sepal length (cm)         instance:    6.1     counter factual:   6.155    difference: -0.054634
sepal width (cm)          instance:    2.8     counter factual:    2.9     difference: -0.1002533
petal length (cm)         instance:    4.7     counter factual:   2.978    difference: 1.7217173
petal width (cm)          instance:    1.2     counter factual:   1.266    difference: -0.0660913
